### PR TITLE
upgrade OTEL version to v1.7.0.

### PR DESCRIPTION
**Pull request by taohe1012**
# Description
upgrade OTEL version to v1.7.0:
 - upgrade otel version to 1.7.0, and its subpackages to v0.30.0;
 - use Async UpDownCounter instead of Sync UpDownCounter;

Note: we upgrade the OpenTelemetry to v1.7.0, and its subpackages to v0.30.0, to use Async UpDownCounter instead of Sync UpDownCounter.

According official reference, [UpDownCounter](https://opentelemetry.io/docs/reference/specification/metrics/api/#updowncounter) :
For fetching the snapshot of the “current value” is straightforward, use Asynchronous UpDownCounter instead, not Synchronous UpDownCounter.

# GitHub Issues

| GitHub Issue # |
| -------------- |
|https://github.com/dell/csm/issues/354 |

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [x] I have maintained at least 90% code coverage
- [x] I have inspected the Grafana dashboards to verify the data is displayed properly
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have maintained backward compatibility

# How Has This Been Tested?

- [x] Test A: UT tests
ut_results

- [x] Test B: Grafana PowerStore Volume IO Metrics: checked it value is consistent with PStore Mgmt UI's volume value
    PStore Mgmt UI:
GUI_vol_performance

    Grafana:
grafana_vol_performance

- [x] Test C: Grafana PowerStore FileSystem IO Metrics: checked it value is consistent with PStore Mgmt UI's nfs volume value
    PStore Mgmt UI:
GUI_nfs_performance

    Grafana:
grafana_nfs_performance

- [x] Test D: Grafana PowerStore Storage Class Capacity:
    Grafana:
grafana_storageclass_cap_1

grafana_storageclass_cap_2_array

grafana_storageclass_cap_3_array

# Manual inspection of the GUI
I have verified that the dashboards show the data properly while generating I/O and storage resources

- [x] Yes
- [ ] No

### CODE REVIEW

**Comment by atye** [comment]
Can one of the admins verify this patch?

**Comment by taohe1012** [comment]
run e2e test

**Review by forrestxia — DISMISSED** [review]

**Review by baoy1 — APPROVED** [review]

**Comment by taohe1012** [comment]
run e2e test

**Comment by taohe1012** [comment]
e2e pass

**Review by shaynafinocchiaro — APPROVED** [review]

**Review by forrestxia — APPROVED** [review]

**Review by baoy1 — APPROVED** [review]

**Review by P-Cao — APPROVED** [review]

**Pull request merged**
