### PR TITLE
Powerstore session

### PR DESCRIPTION
**Pull request by donatwork**
# Description
Update gopowerstore client to use the new session tokens in the client. This will reduce the number of sessions opened when the metrics collection runs.

I want to get this merged in now so we can do some more early testing in the pipelines before we finalize the goclient before release.

| GitHub Issue # |
| -------------- |
|https://github.com/dell/csm/issues/1006|

# Checklist:

- [X] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [x] I have maintained at least 90% code coverage
- [ ] I have inspected the Grafana dashboards to verify the data is displayed properly
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have maintained backward compatibility

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [x] Manual install and verification of metrics connections to the array.
- [ ] 

# Manual inspection of the GUI
I have verified that the dashboards show the data properly while generating I/O and storage resources

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by donatwork** [comment]
run e2e test

**Comment by donatwork** [comment]
run e2e tests

**Review by santhoshatdell — APPROVED** [review]

**Review by santhoshatdell — APPROVED** [review]

**Review by lukeatdell — APPROVED** [review]

**Review by anandrajak1 — APPROVED** [review]

**Comment by donatwork** [comment]
skip e2e test

**Comment by donatwork** [comment]
e2e pass

**Review by anandrajak1 — APPROVED** [review]
e2e pass

**Pull request merged**
